### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-crawler#8]
Currently, we save logs to the database... I'd like whether this is the best approach to it. Would it be better to have a log file?

**Comment by FarazFe** [comment]
@viniciusarre Why not both?

**Comment by viniciusarre** [comment]
That's an idea! The problem in keeping the logs in the database is that it could greatly scale in production (since they grow at a geometric rate).

We could possibly use a cron job to delete old and repeated logs (maybe deleting the ones that are older than a week or so...) 

What do you think? @FarazFe

**Comment by FarazFe** [comment]
@viniciusarre I think it's kinda case-specific. Logging to a file is faster while logging to a database lets you query and inspect the results way better.
So generally, I like the idea of logging to both filesystem and database.
Because in case of network or other types of failures, you can always recover the data.
Another solution is log to the file and if needed, you can migrate them to the database for inspection.

About the issue of log size, running a background job is a good solution. Also, it's possible to limit the size of the log in the filesystem and db.

**Comment by viniciusarre** [comment]
I think there's a new PR solving the file-logging problem... Would you like to work on the background job, @FarazFe?

**Comment by FarazFe** [comment]
@viniciusarre Yes, I'll work on it.

**Comment by FarazFe** [comment]
I created a PR.
Btw did you consider using TTL for log documents?
